[package]
name = "rapier-slow-step"
version = "0.1.0"
authors = ["zaq"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier3d = "0.5"
